service: serverlessPrintConversion

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  apiName: wellsky-print-api
  apiGateway:
    binaryMediaTypes:
      - 'application/pdf'

layers:
  chromeAws:
    path: layers
    artifact: chrome_aws_lambda.zip
    description: Chromium dependencies

package:
  exclude:
    - layers/**

functions:
  pdfCapture:
    handler: src/services/pdf_capture_api.handler
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: api/v1/pdf/capture
          method: get
          cors: true
    layers:
      - { Ref: ChromeAwsLambdaLayer }
